"""LLM judge that marks where a generation's ANSWER begins and ends (no GPU, no regeneration).

Why: under the no-think prefix the base model answers the question and then keeps going
(fake user/assistant turns, a copy of the system prompt, unrelated documents), and ~8% of
generations never answer at all. A regex on role markers recovers about half of the
cap-hitters; this judge handles the rest and the junk. It judges RELEVANCE (is this text
about the question?) and never quality. Every decision is saved next to its gen_id.

Usage:
  python judge_cut.py --inputs base_none=<a.jsonl>,<b.jsonl>,<c.jsonl> no_removal=<d.jsonl> \
                      --out_dir ../results/judge_cut
"""
import argparse, json, random, re, sys, time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent / "lls_owl"))
from judge import client as make_client  # noqa: E402  (reads ANTHROPIC_API_KEY from .env)

MODEL = "claude-sonnet-4-6"          # the blog's judge
MIN_WORDS = 30
RB = re.compile(r"\*\*[^*\n]+\*\*")
RS = re.compile(r"^#{1,6}\s|^\s*[-*]\s", re.M)
DEFAULT_SYSTEM = ("You are Olmo, a helpful AI assistant built by Ai2. Your date cutoff is December 2024, "
                  "and your model weights are available at https://huggingface.co/allenai.")

RUBRIC_VERSION = "v2.1 (2026-10-09): v2 + deflections/refusals that do not attempt the question are not answers; v2 = explicit answering-vs-deliberating distinction; v1 only said to skip leading thinking"
SYSTEM = """You are annotating raw text generated by a language model that was asked a question.
The model is an undertrained base model: sometimes it answers the question and then keeps
going into unrelated material (fake conversation turns, a copy of its system prompt, other
documents, another language); sometimes it never answers at all.

Your job is to mark the span of text that is the model's answer to the question, or say
there is none. You are judging only whether text is ABOUT the question asked, not whether it
answers it well. A wrong, muddled, or incomplete answer to the question still counts as the
answer. Text about something else does not, however good it is.

Rules:
1. The answer is the portion that addresses the question asked. Keep it even if it is
   rambling, repetitive, or wrong, as long as it is about the question. A refusal,
   deflection, or offer to help later that does not attempt the question is not an answer.
2. Distinguish two kinds of text:
   - ANSWERING: addressed to the asker, expository ("Tides are caused by...", "Here are the
     steps:", "1. ...").
   - DELIBERATING: the model talking to itself about how to answer, in first person and
     planning voice ("Okay, the user wants...", "Let me think...", "Wait, isn't there also...",
     "I should mention...", "Maybe I should structure this...", "Now, how to present this...").
   Deliberating is NEVER part of the answer, no matter how much correct, on-topic content it
   contains. The answer STARTS at the first ANSWERING line after any leading deliberation
   (and after any role label on its own line or at the start of a line, e.g. "assistant",
   "Olmo:", "Answer:", "model"). If the text ends while still deliberating and never switches
   to answering, there is no answer: has_answer = false. If an answer later turns back into
   deliberating, the answer ENDS before that.
3. The answer ENDS at the last line before any of the following begins:
   - a new conversation turn (a line like "user", "User:", "assistant", "Human:", "Olmo:")
     or a new question the model poses to itself;
   - a copy or paraphrase of the system prompt ("You are Olmo, a helpful AI assistant...");
   - content unrelated to the question (a different topic, code, a web page, a product
     listing, a quiz);
   - a switch to a different language;
   - text that has stopped being coherent prose about the question.
   If none of these happen, the answer ends at the last line.
4. If no part of the text addresses the question, set has_answer to false.

Reply with JSON only, no prose. Decide "form" first, then the lines:
{"form": "<one of: answering, deliberating_only, deliberating_then_answering, answering_then_deliberating, mixed, none>",
 "has_answer": true|false, "start_line": <int or null>, "end_line": <int or null>,
 "ends_because": "<one of: end_of_text, new_turn, system_prompt_echo, unrelated_content, language_switch, incoherent, deliberating, none>",
 "note": "<at most 15 words>"}
Line numbers refer to the numbered lines in the text and are inclusive."""


def user_msg(prompt, text):
    lines = text.split("\n")
    numbered = "\n".join(f"{i + 1:3d}| {l}" for i, l in enumerate(lines))
    return (f"QUESTION:\n{prompt}\n\nSYSTEM PROMPT THE MODEL WAS GIVEN (for recognising echoes):\n{DEFAULT_SYSTEM}\n\n"
            f"MODEL OUTPUT (numbered lines):\n{numbered}")


def parse_json(s):
    s = s.strip()
    s = re.sub(r"^```(?:json)?\s*|\s*```$", "", s)
    return json.loads(s)


def judge_one(cl, rec, text_field):
    text = rec[text_field]
    if not text.strip():
        return dict(has_answer=False, start_line=None, end_line=None, ends_because="none", note="empty", usage=(0, 0))
    r = cl.with_options(max_retries=5).messages.create(
        model=MODEL, max_tokens=400, system=SYSTEM,
        messages=[{"role": "user", "content": user_msg(rec["prompt"], text)}])
    out = parse_json(r.content[0].text)
    out["usage"] = (r.usage.input_tokens, r.usage.output_tokens)
    return out


def apply_cut(text, j):
    if not j.get("has_answer") or j.get("start_line") is None or j.get("end_line") is None:
        return ""
    lines = text.split("\n")
    a, b = max(1, int(j["start_line"])), min(len(lines), int(j["end_line"]))
    return "\n".join(lines[a - 1:b]).strip() if b >= a else ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inputs", nargs="+", required=True, help="label=path[,path...]")
    ap.add_argument("--text_field", default="text")
    ap.add_argument("--out_dir", default="../results/judge_cut")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()
    out_dir = Path(args.out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    cl = make_client()
    summary = {}
    for spec in args.inputs:
        label, _, paths = spec.partition("=")
        recs = []
        for p in paths.split(","):
            recs += [json.loads(l) for l in open(p)]
        if args.limit: recs = recs[:args.limit]
        t0 = time.time()
        with ThreadPoolExecutor(args.workers) as ex:
            judged = list(ex.map(lambda r: judge_one(cl, r, args.text_field), recs))
        tin = sum(j["usage"][0] for j in judged); tout = sum(j["usage"][1] for j in judged)
        rows = []
        for r, j in zip(recs, judged):
            cut = apply_cut(r[args.text_field], j)
            w = len(cut.split())
            rows.append(dict(gen_id=r["gen_id"], prompt=r["prompt"], judge={k: v for k, v in j.items() if k != "usage"},
                             cut_text=cut, words=w, usable=w >= MIN_WORDS,
                             orig_words=len(r[args.text_field].split()),
                             bold_spans=len(RB.findall(cut)), struct=len(RS.findall(cut))))
        with open(out_dir / f"judged_{label}.jsonl", "w") as f:
            for x in rows: f.write(json.dumps(x) + "\n")
        n = len(rows); us = [x for x in rows if x["usable"]]
        ends = {}
        for x in rows: ends[x["judge"].get("ends_because", "?")] = ends.get(x["judge"].get("ends_because", "?"), 0) + 1
        s = dict(n=n, has_answer=sum(bool(x["judge"].get("has_answer")) for x in rows), usable=len(us),
                 cut_shorter_than_original=sum(x["words"] < x["orig_words"] for x in us),
                 any_bold_usable=float(np.mean([x["bold_spans"] > 0 for x in us])) if us else float("nan"),
                 bold_spans_usable=float(np.mean([x["bold_spans"] for x in us])) if us else float("nan"),
                 any_struct_usable=float(np.mean([x["struct"] > 0 for x in us])) if us else float("nan"),
                 median_words_usable=float(np.median([x["words"] for x in us])) if us else float("nan"),
                 ends_because=ends, input_tokens=tin, output_tokens=tout,
                 cost_usd=round(tin * 3 / 1e6 + tout * 15 / 1e6, 3), seconds=round(time.time() - t0))
        summary[label] = s
        print(f"\n[{label}] {json.dumps(s, indent=1)}", flush=True)
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=1))


if __name__ == "__main__":
    main()
